server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

app:
  jwt:
    secret: "change-me-to-a-long-secret-change-me-to-a-long-secret"
    expiration-minutes: 60

stripe:
  api-key: ${STRIPE_API_KEY:}
  webhook-secret:  whsec_6b3ac0b872f6fe4471b55bdd3018d63893003c33608e563634b97040c61ea19c

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: DEBUG